export const CHAPTER = 'chapter';
export const TRANSITION = 'transition';

export const nodes = [
  {
    id: 'chapter-birthday',
    type: CHAPTER,
    icon: 'birthday',
    year: 1983,
    dates: 'June, 1983',
    title: 'Birthday',
    shortDescription: '1 of 2 children (older sister)',
    location: 'Sulphur, LA',
    readMore: false,
  },
  {
    id: 'chapter-hs-diploma',
    type: CHAPTER,
    icon: 'diploma',
    year: 2001,
    dates: 'May, 2001',
    title: 'Completed High School',
    shortDescription: 'Played on the state-champion Golf Team',
    location: 'Sulphur High School',
    readMore: false,
  },
  {
    id: 'transition-moved-to-baton-rouge',
    type: TRANSITION,
    icon: 'travel-car',
    year: 2001,
    shortDescription: '(moved to Baton Route, LA)',
    readMore: false,
  },
  {
    id: 'chapter-undergrad-degree',
    type: CHAPTER,
    icon: 'degree',
    year: 2005,
    dates: 'December, 2005',
    title: "Complete Bachelor's Degree",
    shortDescription: 'Foreign Languages & Literatures (Latin)',
    longDescription: '',
    location: 'LSU (Baton Rouge)',
    readMore: true,
  },
  {
    id: 'transition-moved-from-baton-rouge-home',
    type: TRANSITION,
    icon: 'travel-car',
    year: 2006,
    shortDescription: '(moved back home (Sulphur / Lake Charles, LA))',
    longDescription: '',
    readMore: true,
  },
  {
    id: 'chapter-paper-plains',
    type: CHAPTER,
    icon: 'music',
    year: 2006,
    dates: 'December, 2005 - August, 2011',
    title: "Played keyboard/piano in 'Paper Plains'",
    shortDescription: 'Indie rock band (wrote original music)',
    location: '(various)',
    readMore: false,
  },
  {
    id: 'chapter-masters-degree',
    type: CHAPTER,
    icon: 'degree',
    year: 2009,
    dates: 'December, 2009',
    title: "Completed Master's Degree",
    shortDescription:
      "Master's in the Arts of Teaching - Foreign Languages / English",
    longDescription: '',
    location: 'Lake Charles, LA',
    readMore: true,
  },
  {
    id: 'chapter-job-high-school-latin',
    type: CHAPTER,
    icon: 'job',
    year: 2009,
    dates: 'August, 2009 - August, 2011',
    title: 'High School Teacher - Latin, Mythology',
    shortDescription: 'Taught Latin I - IV and Mythology',
    longDescription: '',
    location: 'Lake Charles, LA',
    readMore: true,
  },
  {
    id: 'transition-moved-to-spain',
    type: TRANSITION,
    icon: 'travel-plane',
    year: 2011,
    shortDescription: '(moved to Madrid, Spain)',
    longDescription: '',
    readMore: true,
  },
  {
    id: 'chapter-job-teaching-assistant-spain',
    type: CHAPTER,
    icon: 'job',
    year: 2011,
    dates: 'September, 2011 - July, 2013',
    title: 'English Teaching Assistant',
    shortDescription:
      'Assisted teachers in facilitating conversations in English with students',
    longDescription: '',
    location: 'Madrid, Spain',
    readMore: true
  },
  {
    id: 'transition-moved-from-spain-to-home',
    type: TRANSITION,
    icon: 'travel-plane',
    year: 2013,
    shortDescription: '(moved back home (again))',
    readMore: false,
  },
  {
    id: 'chapter-job-high-school-spanish-advanced',
    type: CHAPTER,
    icon: 'job',
    year: 2013,
    dates: 'August, 2013 - May, 2014',
    title: 'High School Teacher - Latin, Spanish',
    shortDescription: 'Taught Spanish II - V',
    longDescription: '',
    location: 'Lake Charles, LA',
    readMore: true,
  },
  {
    id: 'transition-moved-to-austin',
    type: TRANSITION,
    icon: 'travel-car',
    year: 2014,
    shortDescription: '(moved to Austin, TX)',
    readMore: false,
  },
  {
    id: 'chapter-job-high-school-spanish',
    type: CHAPTER,
    icon: 'job',
    year: 2014,
    dates: 'August, 2014 - June, 2016',
    title: 'High School Teacher - Spanish',
    shortDescription: 'Taught Spanish I - II',
    longDescription: '',
    location: 'Dripping Springs, TX',
    readMore: true,
  },
  {
    id: 'chapter-coding-bootcamp-degree',
    type: CHAPTER,
    icon: 'degree',
    year: 2016,
    dates: 'April, 2016 - October, 2016',
    title: 'The Coding Bootcamp at UT Austin',
    shortDescription: 'Learned Web Development in a 6-month intensive bootcamp',
    longDescription: '',
    location: 'Austin, TX',
    readMore: true,
  },
  {
    id: 'chapter-job-zilkr',
    type: CHAPTER,
    icon: 'job',
    year: 2016,
    dates: 'October, 2016 - January, 2018',
    title: 'Software Engineer @ Zilkr Technologies',
    shortDescription: 'Helped build UCAAS developer platform (Nodejs)',
    longDescription:
      "First job as an engineer; worked on a UCAAS developer's platform, using mainly Nodejs (dissolved in 2018)",
    location: 'Austin, TX',
    readMore: true,
  },
  {
    id: 'chapter-celebrate-fatherhood',
    type: CHAPTER,
    icon: 'baby',
    year: 2017,
    dates: 'July, 2017',
    title: 'Became a dad!',
    shortDescription: null,
    location: null,
    readMore: false,
  },
  {
    id: 'chapter-job-scalable',
    type: CHAPTER,
    icon: 'job',
    year: 2018,
    dates: 'February, 2018 - March, 2019',
    title: 'Front-End Web Developer @ Scalable Company',
    shortDescription: 'Helped build CMS app ',
    longDescription:
      'Worked on CMS app (workflow tools for businesses, process documentation, company-wide communication), using client-side Javascript (jQuery) and Ruby on Rails',
    location: 'Austin, TX',
    readMore: true,
  },
  {
    id: 'chapter-job-j-curve',
    type: CHAPTER,
    icon: 'job',
    year: 2019,
    dates: 'April, 2019 - present',
    title: 'Software Engineer @ J-Curve Technologies',
    shortDescription: 'Helping build data analytics tools',
    longDescription:
      'Work on WFM, data aggregation, and reporting app for Contact Center employees, using PostgreSQL, Go, React, Nodejs',
    location: 'remote (HQ in Tempe, AZ)',
    readMore: true,
  },
];
